# remap prefix from 'C-b' to 'C-x'
unbind C-b
set-option -g prefix C-x
bind-key C-x send-prefix

# better split shortcuts
bind h split-window -h
bind v split-window -v
unbind '"'
unbind %
bind -n C-F6 split-window -h
bind -n C-F5 split-window -v

# use mouse
set -g mouse on

# reload config file
bind r source-file ~/.config/tmux/tmux.conf
