- name: Check for rustup
  ansible.builtin.command: rustup --version
  register: rustup_check
  failed_when: false
  changed_when: false

- name: Set rustup_installed fact
  ansible.builtin.set_fact:
    rustup_installed: "{{ rustup_check.rc == 0 }}"

- name: Install rust tooling
  when: not rustup_installed
  ansible.builtin.shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

- name: Specify rust version
  when: not rustup_installed
  ansible.builtin.command: rustup default stable
