- hosts: all
  pre_tasks:
    - name: Load vault variables
      include_vars:
        file: desktop_vault.yml
      when: use_vault | default(false)

  roles:
    - dev
    - shell
    - desktop_notes
    - emacs
    - desktop_configs

  tasks:
    - name: Setup notes and docs backups
      include_role:
        name: backups
      when: (home_pc | default(false)) == true
