- hosts: all
  roles:
    - shell
    - desktop_notes
    - emacs
    - desktop_configs

  tasks:
    - name: Setup notes and docs backups
      include_role:
        name: backups
      when: (home_pc | default(false)) == true
