# requires docker, docker-compose and cron

- name: FTP Server
  hosts: all
  # must be specified when running
  vars:
    server_key: ""
    server_crt: "../vsftpd/vsftpd.pem"
    ftp_users: ""

  tasks:
    - name: Install vsftpd
      ansible.builtin.apt:
        pkg:
          - vsftpd
        update_cache: true
        state: present
      become: true

    - name: Copy the config
      ansible.builtin.copy:
        src: ../vsftpd/vsftpd.conf
        dest: /etc/vsftpd.conf
      become: true

    - name: Copy the private key
      ansible.builtin.copy:
        src: "{{ server_key }}"
        dest: /etc/ssl/private/vsftpd.key
      become: true

    - name: Copy the SSL certificate
      ansible.builtin.copy:
        src: "{{ server_crt }}"
        dest: /etc/ssl/private/vsftpd.pem
      become: true

    - name: Add users to the userlist file
      ansible.builtin.lineinfile:
        path: /etc/vsftpd.userlist
        create: true
        line: "{{ item }}"
      loop: "{{ ftp_users }}"
      become: true

    - name: Reload systemd to pick up the new service unit file
      ansible.builtin.systemd:
        daemon_reload: yes
      become: true

    - name: Enable the service to start on boot
      ansible.builtin.systemd:
        name: vsftpd
        enabled: yes
      become: true

    - name: Start the service
      ansible.builtin.systemd:
        name: vsftpd
        state: started
      become: true
