- name: Setup my desktop
  hosts: all
  tasks:
    - name: Install software
      become: yes
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - git
          - nitrogen
          - kitty
          - rofi
          - vim

    - name: Install Qtile dependencies
      become: yes
      ansible.builtin.apt:
        pkg:
          - libpangocairo-1.0-0
          - python3-pip
          - python3-xcffib
          - python3-cairocffi

    - name: Install Qtile
      ansible.builtin.pip:
        name: qtile

    - name: Copy qtile.desktop
      become: yes
      ansible.builtin.copy:
        src: ../qtile/qtile.desktop
        dest: /usr/share/xsessions/

    - name: Copy qtile config
      ansible.builtin.copy:
        src: ../qtile/config.py
        dest: ~/.config/qtile/

    - name: Copy kitty config
      ansible.builtin.copy:
        src: ../kitty/kitty.conf
        dest: ~/.config/kitty/

    - name: Copy kitty theme
      ansible.builtin.copy:
        src: ../kitty/nord.conf
        dest: ~/.config/kitty/

    - name: Copy rofi config
      ansible.builtin.copy:
        src: ../rofi/config.rasi
        dest: ~/.config/rofi/

    - name: Copy rofi theme
      ansible.builtin.copy:
        src: ../rofi/nord.rasi
        dest: ~/.config/rofi/
