- name: Setup my desktop
  hosts: all
  tasks:
    - name: Install software
      become: yes
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - dunst
          - git
          - kitty
          - nitrogen
          - picom
          - playerctl
          - rofi
          - vim
          - xscreensaver
          - xsecurelock
          - xss-lock
          # qtile dependencies
          - libpangocairo-1.0-0
          - python3-pip
          - python3-xcffib
          - python3-cairocffi


    - name: Install Qtile
      ansible.builtin.pip:
        name: qtile

    - name: Git checkout my dotfiles
      ansible.builtin.git:
        repo: 'https://github.com/sky-mart/Dotfiles.git'
        dest: ~/Dotfiles

    - name: Install my config files
      ansible.builtin.shell: ~/Dotfiles/install.sh
