- name: Install user script
  block:
    - name: Create the user executables directory
      ansible.builtin.file:
        path: ~/.local/bin
        state: directory
        mode: "0755"

    - name: Copy useful scripts
      ansible.builtin.copy:
        src: "{{ item }}.sh"
        dest: "~/.local/bin/{{ item }}.sh"
        mode: 0755
      loop:
        - blconnect
        - kb-layout
        - auto-jbl

    - name: Copy the speaker autoconnection script
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Run script on Plasma unlock
          After=graphical-session.target
          PartOf=graphical-session.target

          [Service]
          Type=simple
          ExecStart=%h/.local/bin/auto-jbl.sh
          Restart=always
          RestartSec=2

          [Install]
          WantedBy=graphical-session.target
        dest: "~/.config/systemd/user/auto-jbl.service"

    - name: Enable the speaker autoconnection service to start on boot
      ansible.builtin.systemd:
        name: auto-jbl.service
        scope: user
        enabled: true
        daemon_reload: true
        force: true
  when: (home_pc | default(false)) == true

- name: Install basic packages
  ansible.builtin.apt:
    pkg:
    - fonts-firacode
    - tmux
    - vim
    update_cache: true
    state: present
  become: true

- name: Check alacritty version
  ansible.builtin.shell: |
    alacritty --version | awk '{print $2}' || true
  register: alacritty_version
  changed_when: false
  failed_when: false

- name: Set alacritty version fact
  ansible.builtin.set_fact:
    installed_alacritty_version: "{{ alacritty_version.stdout | default('') }}"

- name: Install alacritty
  when: installed_alacritty_version != expected_alacritty_version
  ansible.builtin.include_tasks:
    file: install_alacritty.yml

- name: Create tmux config directory
  ansible.builtin.file:
    path: ~/.config/tmux
    state: directory

- name: Create tmux config directory
  ansible.builtin.file:
    path: ~/.config/alacritty/themes
    state: directory

- name: Install tmux config
  block:
    - name: Link tmux config locally
      ansible.builtin.file:
        src: "{{ role_path }}/files/tmux.conf"
        path: "{{ ansible_env.HOME }}/.config/tmux/tmux.conf"
        state: link
        force: true
      when: (ansible_connection | default("ssh")) == "local"

    - name: Copy tmux config remotely
      ansible.builtin.copy:
        src: tmux.conf
        dest: ~/.config/tmux/tmux.conf
      when: (ansible_connection | default('ssh')) != "local"

- name: Install alacritty config
  block:
    - name: Copy alacritty theme
      ansible.builtin.copy:
        src: nord.toml
        dest: ~/.config/alacritty/themes/nord.toml

    - name: Link alacritty config locally
      ansible.builtin.file:
        src: "{{ role_path }}/files/alacritty.toml"
        path: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.toml"
        state: link
        force: true
      when: (ansible_connection | default("ssh")) == "local"

    - name: Copy alacritty config remotely
      ansible.builtin.copy:
        src: alacritty.toml
        dest: ~/.config/alacritty/alacritty.toml
      when: (ansible_connection | default('ssh')) != "local"

- name: Install KDE shortcuts
  ansible.builtin.copy:
    src: kglobalshortcutsrc
    dest: ~/.config/kglobalshortcutsrc
