- name: Install user script
  block:
    - name: Create the user executables directory
      ansible.builtin.file:
        path: ~/.local/bin
        state: directory
        mode: "0755"

    - name: Copy useful scripts
      ansible.builtin.copy:
        src: "{{ item }}.sh"
        dest: "~/.local/bin/{{ item }}.sh"
        mode: 0755
      loop:
        - blconnect
        - kb-layout
        - auto-jbl

    - name: Copy the speaker autoconnection script
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Run script on Plasma unlock
          After=graphical-session.target
          PartOf=graphical-session.target

          [Service]
          Type=simple
          ExecStart=%h/.local/bin/auto-jbl.sh
          Restart=always
          RestartSec=2

          [Install]
          WantedBy=graphical-session.target
        dest: "~/.config/systemd/user/auto-jbl.service"

    - name: Enable the speaker autoconnection service to start on boot
      ansible.builtin.systemd:
        name: auto-jbl.service
        scope: user
        enabled: true
        daemon_reload: true
        force: true
  when: (home_pc | default(false)) == true

- name: Install basic packages
  ansible.builtin.apt:
    pkg:
    - autorandr
    - fonts-firacode
    - brightnessctl
    - bluez
    - dunst
    - flameshot
    - gcc
    - i3blocks
    - i3-wm
    - libx11-dev
    - network-manager
    - picom
    - playerctl
    - pulseaudio-utils
    - rofi
    - tmux
    - vim
    - desktop-file-utils
    - x11-xserver-utils
    - xss-lock
    update_cache: true
    state: present
  become: true

- name: Check alacritty version
  ansible.builtin.shell: |
    alacritty --version | awk '{print $2}' || true
  register: alacritty_version
  changed_when: false
  failed_when: false

- name: Set alacritty version fact
  ansible.builtin.set_fact:
    installed_alacritty_version: "{{ alacritty_version.stdout | default('') }}"

- name: Install alacritty
  when: installed_alacritty_version != expected_alacritty_version
  ansible.builtin.include_tasks:
    file: install_alacritty.yml

- name: Check i3lock version
  ansible.builtin.shell: |
    i3lock --version | awk '{print $2}' || true
  register: i3lock_version
  changed_when: false
  failed_when: false

- name: Set i3lock version fact
  ansible.builtin.set_fact:
    installed_i3lock_version: "{{ i3lock_version.stdout | default('') }}"

- name: Install i3lock-color
  when: installed_i3lock_version != expected_i3lock_color_version
  ansible.builtin.include_tasks:
    file: install_i3lock_color.yml

- name: Create tmux config directory
  ansible.builtin.file:
    path: ~/.config/tmux
    state: directory

- name: Create alacritty config directory
  ansible.builtin.file:
    path: ~/.config/alacritty/themes
    state: directory

- name: Create rofi config directory
  ansible.builtin.file:
    path: ~/.config/rofi
    state: directory

- name: Create i3 config directory
  ansible.builtin.file:
    path: ~/.config/i3
    state: directory

- name: Create i3blocks config directory
  ansible.builtin.file:
    path: ~/.config/i3blocks
    state: directory

- name: Create the user executables directory
  ansible.builtin.file:
    path: ~/.local/bin
    state: directory
    mode: "0755"

- name: Install lock screen script
  block:
    - name: Link lock screen script locally
      ansible.builtin.file:
        src: "{{ role_path }}/files/lock.sh"
        path: "{{ ansible_env.HOME }}/.local/bin/lock.sh"
        state: link
        force: true
      when: (ansible_connection | default("ssh")) == "local"

    - name: Copy lock screen script remotely
      ansible.builtin.copy:
        src: lock.sh
        dest: ~/.local/bin/lock.sh
        mode: 0755
      when: (ansible_connection | default('ssh')) != "local"

- name: Install tmux config
  block:
    - name: Link tmux config locally
      ansible.builtin.file:
        src: "{{ role_path }}/files/tmux.conf"
        path: "{{ ansible_env.HOME }}/.config/tmux/tmux.conf"
        state: link
        force: true
      when: (ansible_connection | default("ssh")) == "local"

    - name: Copy tmux config remotely
      ansible.builtin.copy:
        src: tmux.conf
        dest: ~/.config/tmux/tmux.conf
      when: (ansible_connection | default('ssh')) != "local"

- name: Install alacritty config
  block:
    - name: Copy alacritty theme
      ansible.builtin.copy:
        src: nord.toml
        dest: ~/.config/alacritty/themes/nord.toml

    - name: Link alacritty config locally
      ansible.builtin.file:
        src: "{{ role_path }}/files/alacritty.toml"
        path: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.toml"
        state: link
        force: true
      when: (ansible_connection | default("ssh")) == "local"

    - name: Copy alacritty config remotely
      ansible.builtin.copy:
        src: alacritty.toml
        dest: ~/.config/alacritty/alacritty.toml
      when: (ansible_connection | default('ssh')) != "local"

- name: Install rofi config
  block:
    - name: Link rofi config locally
      ansible.builtin.file:
        src: "{{ role_path }}/files/{{ item.src }}"
        path: "{{ ansible_env.HOME }}/.config/rofi/{{ item.dest }}"
        state: link
        force: true
      loop:
        - { src: rofi.rasi, dest: config.rasi }
        - { src: nord.rasi, dest: nord.rasi }
      when: (ansible_connection | default("ssh")) == "local"

    - name: Copy rofi config remotely
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "~/.config/rofi/{{ item.dest }}"
      loop:
        - { src: rofi.rasi, dest: config.rasi }
        - { src: nord.rasi, dest: nord.rasi }
      when: (ansible_connection | default('ssh')) != "local"

- name: Install i3 config
  block:
    - name: Link i3 config locally
      ansible.builtin.file:
        src: "{{ role_path }}/files/i3.config"
        path: "{{ ansible_env.HOME }}/.config/i3/config"
        state: link
        force: true
      when: (ansible_connection | default("ssh")) == "local"

    - name: Copy i3 config remotely
      ansible.builtin.copy:
        src: i3.config
        dest: ~/.config/i3/config
      when: (ansible_connection | default('ssh')) != "local"

- name: Install i3blocks config
  block:
    - name: Link i3blocks config locally
      ansible.builtin.file:
        src: "{{ role_path }}/files/i3blocks.conf"
        path: "{{ ansible_env.HOME }}/.config/i3blocks/config"
        state: link
        force: true
      when: (ansible_connection | default("ssh")) == "local"

    - name: Copy i3blocks config remotely
      ansible.builtin.copy:
        src: i3blocks.conf
        dest: ~/.config/i3blocks/config
      when: (ansible_connection | default('ssh')) != "local"

- name: Install i3blocks volume script
  block:
    - name: Link i3blocks volume script locally
      ansible.builtin.file:
        src: "{{ role_path }}/files/i3blocks-volume.sh"
        path: "{{ ansible_env.HOME }}/.local/bin/i3blocks-volume.sh"
        state: link
        force: true
      when: (ansible_connection | default("ssh")) == "local"

    - name: Copy i3blocks volume script remotely
      ansible.builtin.copy:
        src: i3blocks-volume.sh
        dest: ~/.local/bin/i3blocks-volume.sh
        mode: 0755
      when: (ansible_connection | default('ssh')) != "local"

- name: Compile the XKB group query helper
  ansible.builtin.command:
    cmd: gcc {{ role_path }}/files/xkb-group.c -o {{ ansible_env.HOME }}/.local/bin/xkb-group -lX11
  changed_when: false
  when: (home_pc | default(false)) == true

- name: Install KDE shortcuts
  ansible.builtin.copy:
    src: kglobalshortcutsrc
    dest: ~/.config/kglobalshortcutsrc
