- name: Create the user executables directory
  ansible.builtin.file:
    path: ~/.local/bin
    state: directory
    mode: "0755"
  when: (home_pc | default(false)) == true

- name: Install fira code font
  ansible.builtin.apt:
    pkg:
    - fonts-firacode
    update_cache: true
    state: present
  become: true

# TODO: install xkb-switch

- name: Copy useful scripts
  ansible.builtin.copy:
    src: "{{ item }}.sh"
    dest: "~/.local/bin/{{ item }}.sh"
    mode: 0755
  loop:
    - blconnect
    - kb-layout
  when: (home_pc | default(false)) == true
